docs_dir: docs/book
site_dir: docs/html
nav:
  - Home: index.md
site_name: oneplace-event
site_description: "onePlace Faucet Telegram Bot"
repo_url: 'https://github.com/OnePlc/PLC_X_Faucet_Tgbot'
theme: bootstrap4
extra:
  project: onePlc